
const columns = [
  {name: "NAME", uid: "name", sortable: true},
  {name: "AGE", uid: "age", sortable: true},
  {name: "PHONE", uid: "phone", sortable: true},
  {name: "EMAIL", uid: "email"},
  {name: "BLOOD GROUP", uid: "bloodGroup"},
  {name: "LAST VISIT", uid: "lastVisit", sortable: true},
  {name: "STATUS", uid: "status", sortable: true},
  {name: "ACTIONS", uid: "actions"},
];

const statusOptions = [
  {name: "Active", uid: "active"},
  {name: "Inactive", uid: "Inactive"},
  {name: "Blcklisted", uid: "blacklisted"},
];

const users = [
  {
    id: 1,
    name: "Tony Reichert",
    phone: "+91 8726539866",
    lastVisit: "26th Feb, 2023",
    status: "active",
    age: "29",
    avatar: "images/user/user-female.jpg",
    bloodGroup: 'O+',
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    phone: "+91 9826539866",
    lastVisit: "28th Nov, 2023",
    status: "inactive",
    age: "25",
    bloodGroup: 'O+',
    avatar: "images/user/user-placeholder.jpg",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    phone: "+91 6653539866",
    lastVisit: "Jan 11th, 2024",
    status: "active",
    age: "22",
    bloodGroup: 'O+',
    avatar: "images/user/user-male.jpg",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    phone: "+91 9263874529",
    lastVisit: "26th Feb, 2023",
    status: "active",
    age: "28",
    bloodGroup: 'O+',
    avatar: "images/user/user-female.jpg",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    phone: "+91 8726539866",
    lastVisit: "26th Feb, 2023",
    status: "active",
    age: "24",
    bloodGroup: 'O+',
    avatar: "images/user/user-placeholder.jpg",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    phone: "+91 8825539866",
    lastVisit: "26th Feb, 2023",
    age: "29",
    bloodGroup: 'O+',
    avatar: "images/user/user-male.jpg",
    email: "brian.kim@example.com",
    status: "blacklisted",
  },
  {
    id: 7,
    name: "Michael Hunt",
    phone: "+91 829339866",
    lastVisit: "26th Feb, 2023",
    status: "inactive",
    age: "27",
    bloodGroup: 'O+',
    avatar: "images/user/user-female.jpg",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    phone: "+91 227339866",
    lastVisit: "26th Feb, 2023",
    status: "active",
    age: "31",
    bloodGroup: 'O+',
    avatar: "images/user/user-male.jpg",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    phone: "+91 9999539866",
    lastVisit: "26th Feb, 2023",
    status: "inactive",
    age: "33",
    bloodGroup: 'O+',
    avatar: "images/user/user-female.jpg",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    phone: "+91 9287539866",
    lastVisit: "26th Feb, 2023",
    status: "blacklisted",
    age: "35",
    bloodGroup: 'O+',
    avatar: "images/user/user-placeholder.jpg",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    phone: "+91 228379866",
    lastVisit: "26th Feb, 2023",
    status: "active",
    age: "22",
    bloodGroup: 'O+',
    avatar: "images/user/user-male.jpg",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    phone: "+91 928736866",
    lastVisit: "26th Feb, 2023",
    status: "inactive",
    age: "28",
    bloodGroup: 'O+',
    avatar: "images/user/user-placeholder.jpg",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    phone: "+91 0298376866",
    lastVisit: "26th Feb, 2023",
    status: "active",
    age: "37",
    bloodGroup: 'O+',
    avatar: "images/user/user-male.jpg",
    email: "oliver.scott@example.com",
  },
];

export {columns, users, statusOptions};
