export const IndianStatesList = [
    { label: "Andhra Pradesh", value: "andhra_pradesh", description: "State in Southern India" },
    { label: "Arunachal Pradesh", value: "arunachal_pradesh", description: "State in Northeast India" },
    { label: "Assam", value: "assam", description: "State in Northeast India" },
    { label: "Bihar", value: "bihar", description: "State in Eastern India" },
    { label: "Chhattisgarh", value: "chhattisgarh", description: "State in Central India" },
    { label: "Goa", value: "goa", description: "State in Western India" },
    { label: "Gujarat", value: "gujarat", description: "State in Western India" },
    { label: "Haryana", value: "haryana", description: "State in Northern India" },
    { label: "Himachal Pradesh", value: "himachal_pradesh", description: "State in Northern India" },
    { label: "Jammu and Kashmir", value: "jammu_and_kashmir", description: "Union territory in Northern India" },
    { label: "Jharkhand", value: "jharkhand", description: "State in Eastern India" },
    { label: "Karnataka", value: "karnataka", description: "State in Southern India" },
    { label: "Kerala", value: "kerala", description: "State in Southern India" },
    { label: "Madhya Pradesh", value: "madhya_pradesh", description: "State in Central India" },
    { label: "Maharashtra", value: "maharashtra", description: "State in Western India" },
    { label: "Manipur", value: "manipur", description: "State in Northeast India" },
    { label: "Meghalaya", value: "meghalaya", description: "State in Northeast India" },
    { label: "Mizoram", value: "mizoram", description: "State in Northeast India" },
    { label: "Nagaland", value: "nagaland", description: "State in Northeast India" },
    { label: "Odisha", value: "odisha", description: "State in Eastern India" },
    { label: "Punjab", value: "punjab", description: "State in Northern India" },
    { label: "Rajasthan", value: "rajasthan", description: "State in Northern India" },
    { label: "Sikkim", value: "sikkim", description: "State in Northeast India" },
    { label: "Tamil Nadu", value: "tamil_nadu", description: "State in Southern India" },
    { label: "Telangana", value: "telangana", description: "State in Southern India" },
    { label: "Tripura", value: "tripura", description: "State in Northeast India" },
    { label: "Uttarakhand", value: "uttarakhand", description: "State in Northern India" },
    { label: "Uttar Pradesh", value: "uttar_pradesh", description: "State in Northern India" },
    { label: "West Bengal", value: "west_bengal", description: "State in Eastern India" },
    { label: "Andaman and Nicobar Islands", value: "andaman_and_nicobar_islands", description: "Union territory in Eastern India" },
    { label: "Chandigarh", value: "chandigarh", description: "Union territory in Northern India" },
    { label: "Dadra and Nagar Haveli", value: "dadra_and_nagar_haveli", description: "Union territory in Western India" },
    { label: "Daman and Diu", value: "daman_and_diu", description: "Union territory in Western India" },
    { label: "Delhi", value: "delhi", description: "Union territory and capital city of India" },
    { label: "Lakshadweep", value: "lakshadweep", description: "Union territory in Southern India" },
    { label: "Puducherry", value: "puducherry", description: "Union territory in Southern India" }
  ];
  

export const stateAbbrivations = [
    ["Andhra Pradesh", "AP"],
    ["Arunachal Pradesh", "AR"],
    ["Assam", "AS"],
    ["Bihar", "BR"],
    ["Chhattisgarh", "CG"],
    ["Goa", "GA"],
    ["Gujarat", "GJ"],
    ["Haryana", "HR"],
    ["Himachal Pradesh", "HP"],
    ["Jammu and Kashmir", "JK"],
    ["Jharkhand", "JH"],
    ["Karnataka", "KA"],
    ["Kerala", "KL"],
    ["Madhya Pradesh", "MP"],
    ["Maharashtra", "MH"],
    ["Manipur", "MN"],
    ["Meghalaya", "ML"],
    ["Mizoram", "MZ"],
    ["Nagaland", "NL"],
    ["Odisha", "OD"],
    ["Punjab", "PB"],
    ["Rajasthan", "RJ"],
    ["Sikkim", "SK"],
    ["Tamil Nadu", "TN"],
    ["Telangana", "TS"],
    ["Tripura", "TR"],
    ["Uttarakhand", "UK"],
    ["Uttar Pradesh", "UP"],
    ["West Bengal", "WB"],
    ["Andaman and Nicobar Islands", "AN"],
    ["Chandigarh", "CH"],
    ["Dadra and Nagar Haveli", "DN"],
    ["Daman and Diu", "DD"],
    ["Delhi", "DL"],
    ["Lakshadweep", "LD"],
    ["Puducherry", "PY"]
]